/*
  Warnings:

  - Existing values in `FileChunk.embedding` are cleared because they were
    generated by a different embedding model (Xenova/all-MiniLM-L6-v2,
    384 dims) and are not compatible with the new model
    (qwen/qwen3-embedding-0.6b via OpenRouter, 1024 dims). Affected files
    must be re-embedded.

*/
-- Clear stale embeddings from the previous model before widening the column
UPDATE "FileChunk" SET "embedding" = NULL;

-- DropIndex
DROP INDEX "FileChunk_embedding_idx";

-- AlterTable
ALTER TABLE "FileChunk" ALTER COLUMN "embedding" TYPE vector(1024);

-- CreateIndex (ANN index for similarity search; Prisma cannot express this natively)
CREATE INDEX "FileChunk_embedding_idx" ON "FileChunk" USING hnsw ("embedding" vector_cosine_ops);
